travis:
  secure:
    BINSTAR_TOKEN: IVD8iHKPztQ8DhwWKeqL++OJ0+zF7KbFAGhuu1wvS/jMGYUQcDaoQdDaBRflc1biB+Ol5CgtViqfLj7fz20UiCrbch7YC6a8fH3hs0Kj+vMd8MVo9+5Bv9Zl5/QYR21ZgGi/Sq4JKtjmp/JdRk1S02QzrB83asxOBrfSF4aOFglbJislz0U2kUhwiSedimLOVRZrA8a0c+87kt9gOhNEXcoSvjbKc1EemEWFBAwfXc4LZ/oSiL4HNEvkdZybS7QKjcbwDdzbUOiAzx+QwHOk4LHhhQz3hmSzPrW2VWuFOEhLS/+ciyxoHic2LPsEYcgFSP0893TEIOqvS94fk0VbaKKrN2vMkU0jUvw/kcRy9nj5OnIAMogqRQry4Hm2GiaTjGyg3cqXHLV1SmYRspq60tm3xLRunpONtOS+SLS5G73QxSQF+qAWL+n318v8a3yHhIue5LtPpXosEOBBOhlD6K2H0qURpfDywiAxDD45wsaJ4gFNPUc4rSPeG944Fq2mkmykF224cwh1Y5Jj7O4QWLY/fRiZIGT05Ewzg7RhyeG1LYuLDw1mp/uDsCoc1Dd+uXALT4uwEUwh0FOln8+D4NY9HrARXlnHu3MfV0qpPsXZg9uxLKddG7DPg28ZM14FTBup9UMG9XaEzvSRV6m/Z9jsKUTtVEYZedp3JM+pK2k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
